name: marble_cli
description: CLI tools used to build and run Marble sites
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  mason_logger: ^0.1.0-dev.12
  path: ^1.8.2
  pub_updater: ^0.2.1

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1

executables:
  marble_cli:
