name: marble_frog
description: Provides marble support to dart frog
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  marble: 1.0.0+1
  dart_frog: ^0.0.1-dev.10

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
