name: marble_flog

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/marble_flog.yaml
      - packages/marble_flog/**

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/marble_flog.yaml
      - packages/marble_flog/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@main

      - name: Install Dependencies
        run: melos bootstrap

      - name: Format
        run: melos exec --scope marble_flog dart format --set-exit-if-changed lib

      - name: Analyze
        run: melos exec --scope marble_flog dart analyze --fatal-infos --fatal-warnings .

      - name: Run Tests
        run: melos exec --scope marble_flog flutter test
